# Generated by Django 5.2.6 on 2025-09-23 03:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ID must be numeric and up to 8 digits.",
                                regex="^\\d{1,8}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "course_year_section",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "college",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CAS", "College of Arts and Sciences"),
                            ("CIT", "College of Industrial Technology"),
                            ("COE", "College of Engineering"),
                            ("CBMA", "College of Business Management and Accountancy"),
                            ("CCS", "College of Computer Studies"),
                            ("COED", "College of Education"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("noted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offense",
                    models.CharField(
                        help_text="(Provide your reason or explanation why the violation occurred. Include any circumstances you want the Office of Student Affairs to consider.)",
                        max_length=255,
                        verbose_name="Reason for the Offense / Student’s Explanation",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First Offense"),
                            (2, "Second Offense"),
                            (3, "Third Offense"),
                        ],
                        default=1,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="tracker.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
