# Generated by Django 5.2.6 on 2025-09-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="college",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAS", "College of Arts and Sciences"),
                    ("CIT", "College of Industrial Technology"),
                    ("COE", "College of Engineering"),
                    ("CBMA", "College of Business Management and Accountancy"),
                    ("CCS", "College of Computer Studies"),
                    ("COED", "College of Education"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="course_year_section",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="violation",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Select Offense Level"),
                    (2, "First Offense"),
                    (3, "Second Offense"),
                    (4, "Third Offense"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="violation",
            name="offense",
            field=models.CharField(
                help_text="(Provide your reason or explanation why the violation occurred. Include any circumstances you want the Office of Student Affairs to consider.)",
                max_length=255,
                verbose_name="Reason for the Offense / Student’s Explanation",
            ),
        ),
    ]
