# Generated by Django 5.2.6 on 2025-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_student_college_student_course_year_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
