# Generated by Django 5.2.6 on 2025-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
