# Generated by Django 5.2.6 on 2025-09-20 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ID must be numeric and up to 8 digits.",
                        regex="^\\d{1,8}$",
                    )
                ],
            ),
        ),
    ]
