# Generated by Django 4.0.1 on 2025-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select Offense Level'), (1, 'First Offense'), (2, 'Second Offense'), (3, 'Third Offense')], default=1),
        ),
    ]
